// Bundled open-data plant catalogue.
// Care values compiled from open horticultural sources (typical household conditions).
// waterSummer / waterWinter: days between waterings in growing vs dormant season.
// mist: days between mistings (null = doesn't need misting).
// fertilize: days between fertilizing during growing season.
// light: 'direct' | 'partial' | 'shade'
// outdoor: can live outside (rain can count toward its watering).
// icon: id of a built-in stylized icon in PlantIcons.jsx
// details / pot: defaults used to fill the Gemini icon-generation prompt.
//
// Plants added from the online (Perenual) search are stored in app state and
// registered here at runtime via setCustomCatalog().

export const LIGHT_LABELS = {
  direct:  'Direct sun',
  partial: 'Partial sun',
  shade:   'Shade',
}

export const CATEGORIES = [
  ['all',       'All'],
  ['foliage',   'Foliage'],
  ['cactus',    'Cacti'],
  ['succulent', 'Succulents'],
  ['flower',    'Flowers'],
  ['herb',      'Herbs & edible'],
  ['tree',      'Trees & palms'],
]

export const CATALOG = [
  /* ── foliage / classic houseplants ── */
  { id: 'peace-lily',      name: 'Peace Lily',          latin: 'Spathiphyllum wallisii',   category: 'foliage', light: 'partial', waterSummer: 5,  waterWinter: 9,  mist: 7,    fertilize: 42, outdoor: false, icon: 'peaceLily',  details: 'glossy dark leaves and one white hooded flower', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'monstera',        name: 'Monstera',            latin: 'Monstera deliciosa',       category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 30, outdoor: false, icon: 'monstera',   details: 'large split heart-shaped leaves', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'monstera-adansonii', name: 'Monstera Adansonii', latin: 'Monstera adansonii',    category: 'foliage', light: 'partial', waterSummer: 6,  waterWinter: 10, mist: 5,    fertilize: 30, outdoor: false, icon: 'monstera',   details: 'small leaves with oval holes on thin vines', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'pothos',          name: 'Pothos',              latin: 'Epipremnum aureum',        category: 'foliage', light: 'shade',   waterSummer: 8,  waterWinter: 12, mist: null, fertilize: 45, outdoor: false, icon: 'leafVine',   details: 'trailing heart-shaped leaves with golden variegation', pot: 'hanging pot', potColor: 'sage green' },
  { id: 'snake-plant',     name: 'Snake Plant',         latin: 'Dracaena trifasciata',     category: 'foliage', light: 'partial', waterSummer: 14, waterWinter: 28, mist: null, fertilize: 60, outdoor: false, icon: 'snakePlant', details: 'tall upright sword leaves with yellow edges', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'zz-plant',        name: 'ZZ Plant',            latin: 'Zamioculcas zamiifolia',   category: 'foliage', light: 'shade',   waterSummer: 14, waterWinter: 28, mist: null, fertilize: 60, outdoor: false, icon: 'leafVine',   details: 'arching stems of waxy oval leaflets', pot: 'ceramic pot', potColor: 'charcoal grey' },
  { id: 'spider-plant',    name: 'Spider Plant',        latin: 'Chlorophytum comosum',     category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: null, fertilize: 30, outdoor: false, icon: 'grassy',     details: 'arching striped grass-like leaves with plantlets', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'boston-fern',     name: 'Boston Fern',         latin: 'Nephrolepis exaltata',     category: 'foliage', light: 'shade',   waterSummer: 4,  waterWinter: 7,  mist: 3,    fertilize: 30, outdoor: true,  icon: 'fern',       details: 'a full mound of arching feathery fronds', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'calathea',        name: 'Calathea',            latin: 'Calathea orbifolia',       category: 'foliage', light: 'shade',   waterSummer: 5,  waterWinter: 9,  mist: 3,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'round striped leaves like brushed silver', pot: 'ceramic pot', potColor: 'mint green' },
  { id: 'philodendron',    name: 'Philodendron',        latin: 'Philodendron hederaceum',  category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 10, mist: 7,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'trailing heart-shaped emerald leaves', pot: 'hanging pot', potColor: 'sage green' },
  { id: 'english-ivy',     name: 'English Ivy',         latin: 'Hedera helix',             category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 10, mist: 5,    fertilize: 30, outdoor: true,  icon: 'leafVine',   details: 'trailing pointed ivy leaves', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'lucky-bamboo',    name: 'Lucky Bamboo',        latin: 'Dracaena sanderiana',      category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 7,  mist: null, fertilize: 90, outdoor: false, icon: 'bamboo',     details: 'green bamboo stalks with small leaf shoots', pot: 'glass vase', potColor: 'clear' },
  { id: 'peperomia',       name: 'Peperomia',           latin: 'Peperomia obtusifolia',    category: 'foliage', light: 'partial', waterSummer: 8,  waterWinter: 12, mist: null, fertilize: 45, outdoor: false, icon: 'leafVine',   details: 'compact rippled coin-shaped leaves', pot: 'small ceramic pot', potColor: 'cream white' },
  { id: 'dracaena',        name: 'Dracaena',            latin: 'Dracaena marginata',       category: 'foliage', light: 'partial', waterSummer: 8,  waterWinter: 14, mist: 7,    fertilize: 45, outdoor: false, icon: 'grassy',     details: 'thin arching red-edged leaves on slim canes', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'croton',          name: 'Croton',              latin: 'Codiaeum variegatum',      category: 'foliage', light: 'direct',  waterSummer: 5,  waterWinter: 8,  mist: 5,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'fiery multicolored veined leaves', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'dieffenbachia',   name: 'Dieffenbachia',       latin: 'Dieffenbachia seguine',    category: 'foliage', light: 'partial', waterSummer: 6,  waterWinter: 10, mist: 5,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'broad cream-splashed tropical leaves', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'hoya',            name: 'Hoya',                latin: 'Hoya carnosa',             category: 'foliage', light: 'partial', waterSummer: 10, waterWinter: 18, mist: null, fertilize: 45, outdoor: false, icon: 'leafVine',   details: 'waxy trailing leaves with star flower clusters', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'tradescantia',    name: 'Tradescantia',        latin: 'Tradescantia zebrina',     category: 'foliage', light: 'partial', waterSummer: 6,  waterWinter: 9,  mist: null, fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'trailing purple-striped shimmering leaves', pot: 'hanging pot', potColor: 'sage green' },
  { id: 'oxalis',          name: 'Oxalis',              latin: 'Oxalis triangularis',      category: 'foliage', light: 'partial', waterSummer: 6,  waterWinter: 10, mist: null, fertilize: 30, outdoor: true,  icon: 'flowerBunch', details: 'purple butterfly-shaped triangle leaves', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'yucca',           name: 'Yucca',               latin: 'Yucca elephantipes',       category: 'foliage', light: 'direct',  waterSummer: 10, waterWinter: 21, mist: null, fertilize: 60, outdoor: true,  icon: 'grassy',     details: 'spiky sword leaves atop a woody cane', pot: 'ceramic pot', potColor: 'charcoal grey' },
  { id: 'alocasia',        name: 'Alocasia',            latin: 'Alocasia amazonica',       category: 'foliage', light: 'partial', waterSummer: 5,  waterWinter: 9,  mist: 3,    fertilize: 30, outdoor: false, icon: 'monstera',   details: 'dramatic arrow-shaped leaves with white veins', pot: 'ceramic pot', potColor: 'charcoal grey' },
  { id: 'pilea',           name: 'Chinese Money Plant', latin: 'Pilea peperomioides',      category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: null, fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'round coin-shaped leaves on thin stems', pot: 'small ceramic pot', potColor: 'mint green' },
  { id: 'fittonia',        name: 'Nerve Plant',         latin: 'Fittonia albivenis',       category: 'foliage', light: 'shade',   waterSummer: 4,  waterWinter: 7,  mist: 3,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'small leaves webbed with pink veins', pot: 'small ceramic pot', potColor: 'cream white' },
  { id: 'polka-dot',       name: 'Polka Dot Plant',     latin: 'Hypoestes phyllostachya',  category: 'foliage', light: 'partial', waterSummer: 4,  waterWinter: 8,  mist: 3,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'leaves speckled with pink dots', pot: 'small ceramic pot', potColor: 'mint green' },
  { id: 'prayer-plant',    name: 'Prayer Plant',        latin: 'Maranta leuconeura',       category: 'foliage', light: 'shade',   waterSummer: 5,  waterWinter: 9,  mist: 3,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'oval leaves painted with red herringbone veins', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'cast-iron',       name: 'Cast Iron Plant',     latin: 'Aspidistra elatior',       category: 'foliage', light: 'shade',   waterSummer: 10, waterWinter: 18, mist: null, fertilize: 60, outdoor: true,  icon: 'grassy',     details: 'tough upright deep-green blade leaves', pot: 'ceramic pot', potColor: 'charcoal grey' },
  { id: 'aglaonema',       name: 'Aglaonema',           latin: 'Aglaonema commutatum',     category: 'foliage', light: 'shade',   waterSummer: 8,  waterWinter: 12, mist: 7,    fertilize: 45, outdoor: false, icon: 'leafVine',   details: 'lance leaves marbled silver and green', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'syngonium',       name: 'Arrowhead Plant',     latin: 'Syngonium podophyllum',    category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 10, mist: 5,    fertilize: 30, outdoor: false, icon: 'leafVine',   details: 'soft arrow-shaped leaves in pale green', pot: 'hanging pot', potColor: 'sage green' },
  { id: 'asparagus-fern',  name: 'Asparagus Fern',      latin: 'Asparagus setaceus',       category: 'foliage', light: 'partial', waterSummer: 5,  waterWinter: 8,  mist: 3,    fertilize: 30, outdoor: true,  icon: 'fern',       details: 'a cloud of feathery needle-soft foliage', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'air-plant',       name: 'Air Plant',           latin: 'Tillandsia ionantha',      category: 'foliage', light: 'partial', waterSummer: 7,  waterWinter: 10, mist: 3,    fertilize: 60, outdoor: false, icon: 'grassy',     details: 'a rootless rosette of silvery curved spikes', pot: 'glass terrarium', potColor: 'clear' },

  /* ── cacti ── */
  { id: 'cactus',          name: 'Columnar Cactus',     latin: 'Cactaceae',                category: 'cactus', light: 'direct', waterSummer: 14, waterWinter: 35, mist: null, fertilize: 60, outdoor: true,  icon: 'cactus', details: 'a plump columnar cactus with tiny spines', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'golden-barrel',   name: 'Golden Barrel Cactus', latin: 'Echinocactus grusonii',   category: 'cactus', light: 'direct', waterSummer: 14, waterWinter: 40, mist: null, fertilize: 90, outdoor: true,  icon: 'cactus', details: 'a round barrel cactus with golden ribs of spines', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'prickly-pear',    name: 'Prickly Pear',        latin: 'Opuntia ficus-indica',     category: 'cactus', light: 'direct', waterSummer: 14, waterWinter: 35, mist: null, fertilize: 60, outdoor: true,  icon: 'cactus', details: 'flat paddle-shaped cactus pads', pot: 'terracotta pot', potColor: 'sand beige' },
  { id: 'bunny-ears',      name: 'Bunny Ears Cactus',   latin: 'Opuntia microdasys',       category: 'cactus', light: 'direct', waterSummer: 14, waterWinter: 35, mist: null, fertilize: 90, outdoor: true,  icon: 'cactus', details: 'two ear-like pads dotted with fuzzy glochids', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'christmas-cactus', name: 'Christmas Cactus',   latin: 'Schlumbergera bridgesii',  category: 'cactus', light: 'partial', waterSummer: 7, waterWinter: 14, mist: null, fertilize: 30, outdoor: false, icon: 'cactus', details: 'arching segmented stems tipped with fuchsia blooms', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'moon-cactus',     name: 'Moon Cactus',         latin: 'Gymnocalycium mihanovichii', category: 'cactus', light: 'partial', waterSummer: 12, waterWinter: 30, mist: null, fertilize: 90, outdoor: false, icon: 'cactus', details: 'a bright pink grafted ball atop a green cactus stem', pot: 'small ceramic pot', potColor: 'mint green' },
  { id: 'pincushion',      name: 'Pincushion Cactus',   latin: 'Mammillaria crinita',      category: 'cactus', light: 'direct', waterSummer: 14, waterWinter: 40, mist: null, fertilize: 90, outdoor: true,  icon: 'cactus', details: 'a small round cactus ringed with tiny pink flowers', pot: 'small ceramic pot', potColor: 'warm orange' },
  { id: 'bishops-cap',     name: "Bishop's Cap",        latin: 'Astrophytum myriostigma',  category: 'cactus', light: 'direct', waterSummer: 16, waterWinter: 45, mist: null, fertilize: 90, outdoor: true,  icon: 'cactus', details: 'a star-shaped ribbed cactus with speckled skin', pot: 'terracotta pot', potColor: 'sand beige' },
  { id: 'fairy-castle',    name: 'Fairy Castle Cactus', latin: 'Acanthocereus tetragonus', category: 'cactus', light: 'direct', waterSummer: 14, waterWinter: 35, mist: null, fertilize: 90, outdoor: true,  icon: 'cactus', details: 'clustered turrets of ribbed green columns', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'peruvian-apple',  name: 'Peruvian Apple Cactus', latin: 'Cereus repandus',        category: 'cactus', light: 'direct', waterSummer: 14, waterWinter: 35, mist: null, fertilize: 60, outdoor: true,  icon: 'cactus', details: 'a tall blue-green columnar cactus', pot: 'ceramic pot', potColor: 'charcoal grey' },

  /* ── succulents ── */
  { id: 'aloe',            name: 'Aloe Vera',           latin: 'Aloe barbadensis miller',  category: 'succulent', light: 'direct', waterSummer: 14, waterWinter: 28, mist: null, fertilize: 90, outdoor: true,  icon: 'succulent', details: 'thick fleshy pointed leaves in a rosette', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'echeveria',       name: 'Echeveria',           latin: 'Echeveria elegans',        category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 25, mist: null, fertilize: 90, outdoor: true,  icon: 'succulent', details: 'a compact pastel rosette succulent', pot: 'small ceramic pot', potColor: 'mint green' },
  { id: 'jade',            name: 'Jade Plant',          latin: 'Crassula ovata',           category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 21, mist: null, fertilize: 60, outdoor: true,  icon: 'bonsai', details: 'a mini tree with plump round jade leaves', pot: 'ceramic bowl', potColor: 'cream white' },
  { id: 'string-pearls',   name: 'String of Pearls',    latin: 'Senecio rowleyanus',       category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 24, mist: null, fertilize: 60, outdoor: false, icon: 'succulent', details: 'cascading strings of round pearl-like beads', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'haworthia',       name: 'Zebra Haworthia',     latin: 'Haworthiopsis attenuata',  category: 'succulent', light: 'partial', waterSummer: 12, waterWinter: 25, mist: null, fertilize: 90, outdoor: false, icon: 'succulent', details: 'a dark rosette striped with white zebra bands', pot: 'small ceramic pot', potColor: 'charcoal grey' },
  { id: 'burros-tail',     name: "Burro's Tail",        latin: 'Sedum morganianum',        category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 28, mist: null, fertilize: 90, outdoor: true,  icon: 'succulent', details: 'trailing ropes of plump overlapping leaves', pot: 'hanging pot', potColor: 'sand beige' },
  { id: 'lithops',         name: 'Living Stones',       latin: 'Lithops hookeri',          category: 'succulent', light: 'direct', waterSummer: 21, waterWinter: 60, mist: null, fertilize: 120, outdoor: false, icon: 'succulent', details: 'a pair of pebble-like split leaves', pot: 'small ceramic pot', potColor: 'sand beige' },
  { id: 'agave',           name: 'Agave',               latin: 'Agave americana',          category: 'succulent', light: 'direct', waterSummer: 14, waterWinter: 35, mist: null, fertilize: 90, outdoor: true,  icon: 'succulent', details: 'a bold rosette of thick spiked blue-green leaves', pot: 'terracotta pot', potColor: 'sand beige' },
  { id: 'hens-chicks',     name: 'Hens and Chicks',     latin: 'Sempervivum tectorum',     category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 30, mist: null, fertilize: 90, outdoor: true,  icon: 'succulent', details: 'a mother rosette ringed by tiny offsets', pot: 'shallow bonsai dish', potColor: 'warm orange' },
  { id: 'panda-plant',     name: 'Panda Plant',         latin: 'Kalanchoe tomentosa',      category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 28, mist: null, fertilize: 90, outdoor: false, icon: 'succulent', details: 'fuzzy silver leaves edged in chocolate brown', pot: 'small ceramic pot', potColor: 'cream white' },
  { id: 'crown-of-thorns', name: 'Crown of Thorns',     latin: 'Euphorbia milii',          category: 'succulent', light: 'direct', waterSummer: 9,  waterWinter: 18, mist: null, fertilize: 30, outdoor: true,  icon: 'rose', details: 'thorny stems crowned with small coral-red blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'elephant-bush',   name: 'Elephant Bush',       latin: 'Portulacaria afra',        category: 'succulent', light: 'direct', waterSummer: 10, waterWinter: 24, mist: null, fertilize: 60, outdoor: true,  icon: 'bonsai', details: 'red stems packed with tiny round jade leaves', pot: 'ceramic bowl', potColor: 'warm orange' },
  { id: 'blue-chalk',      name: 'Blue Chalksticks',    latin: 'Senecio mandraliscae',     category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 28, mist: null, fertilize: 90, outdoor: true,  icon: 'succulent', details: 'upright fingers of powdery blue foliage', pot: 'terracotta pot', potColor: 'sand beige' },
  { id: 'aeonium',         name: 'Aeonium',             latin: 'Aeonium arboreum',         category: 'succulent', light: 'direct', waterSummer: 10, waterWinter: 21, mist: null, fertilize: 60, outdoor: true,  icon: 'succulent', details: 'glossy rosettes on branching stems', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'gasteria',        name: 'Gasteria',            latin: 'Gasteria bicolor',         category: 'succulent', light: 'partial', waterSummer: 14, waterWinter: 30, mist: null, fertilize: 90, outdoor: false, icon: 'succulent', details: 'thick tongue-shaped speckled leaves in a fan', pot: 'small ceramic pot', potColor: 'charcoal grey' },
  { id: 'ghost-plant',     name: 'Ghost Plant',         latin: 'Graptopetalum paraguayense', category: 'succulent', light: 'direct', waterSummer: 12, waterWinter: 28, mist: null, fertilize: 90, outdoor: true, icon: 'succulent', details: 'pale opalescent rosettes on trailing stems', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'string-of-hearts', name: 'String of Hearts',   latin: 'Ceropegia woodii',         category: 'succulent', light: 'partial', waterSummer: 10, waterWinter: 20, mist: null, fertilize: 45, outdoor: false, icon: 'leafVine', details: 'delicate trailing vines of marbled heart leaves', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'flaming-katy',    name: 'Flaming Katy',        latin: 'Kalanchoe blossfeldiana',  category: 'succulent', light: 'direct', waterSummer: 8,  waterWinter: 16, mist: null, fertilize: 30, outdoor: false, icon: 'flowerBunch', details: 'scalloped leaves under clusters of tiny bright blooms', pot: 'small ceramic pot', potColor: 'warm orange' },

  /* ── flowering plants ── */
  { id: 'zinnia',          name: 'Zinnia',              latin: 'Zinnia elegans',           category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 21, outdoor: true,  icon: 'daisy', details: 'bright layered pom-pom zinnia blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'rose',            name: 'Rose (potted)',       latin: 'Rosa chinensis',           category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 21, outdoor: true,  icon: 'rose', details: 'a deep red rose bloom with layered petals', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'tulip',           name: 'Tulip (potted)',      latin: 'Tulipa gesneriana',        category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 7,  mist: null, fertilize: 30, outdoor: true,  icon: 'tulip', details: 'two soft pink tulip blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'daisy',           name: 'Daisy',               latin: 'Bellis perennis',          category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 30, outdoor: true,  icon: 'daisy', details: 'cheerful white daisies with yellow centers', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'orchid',          name: 'Orchid',              latin: 'Phalaenopsis',             category: 'flower', light: 'partial', waterSummer: 7, waterWinter: 10, mist: 5,    fertilize: 30, outdoor: false, icon: 'tulip', details: 'an arching stem of moth orchid blooms', pot: 'clear orchid pot', potColor: 'clear' },
  { id: 'anthurium',       name: 'Anthurium',           latin: 'Anthurium andraeanum',     category: 'flower', light: 'partial', waterSummer: 6, waterWinter: 9,  mist: 5,    fertilize: 42, outdoor: false, icon: 'rose', details: 'glossy red heart-shaped flowers', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'begonia',         name: 'Begonia',             latin: 'Begonia semperflorens',    category: 'flower', light: 'partial', waterSummer: 5, waterWinter: 8,  mist: null, fertilize: 30, outdoor: true,  icon: 'rose', details: 'clusters of soft pink blooms and round leaves', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'african-violet',  name: 'African Violet',      latin: 'Saintpaulia ionantha',     category: 'flower', light: 'partial', waterSummer: 5, waterWinter: 7,  mist: null, fertilize: 30, outdoor: false, icon: 'flowerBunch', details: 'velvet leaves with purple violet flowers', pot: 'small ceramic pot', potColor: 'mint green' },
  { id: 'hydrangea',       name: 'Hydrangea',           latin: 'Hydrangea macrophylla',    category: 'flower', light: 'partial', waterSummer: 3, waterWinter: 5,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'a large pastel pom-pom flower head', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'geranium',        name: 'Geranium',            latin: 'Pelargonium hortorum',     category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 8,  mist: null, fertilize: 21, outdoor: true,  icon: 'rose', details: 'clusters of bright coral blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'hibiscus',        name: 'Hibiscus',            latin: 'Hibiscus rosa-sinensis',   category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 21, outdoor: true,  icon: 'rose', details: 'a wide tropical trumpet flower', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'bougainvillea',   name: 'Bougainvillea',       latin: 'Bougainvillea glabra',     category: 'flower', light: 'direct',  waterSummer: 5, waterWinter: 10, mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'cascading magenta paper-like blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'marigold',        name: 'Marigold',            latin: 'Tagetes erecta',           category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 21, outdoor: true,  icon: 'daisy', details: 'ruffled golden-orange marigold blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'petunia',         name: 'Petunia',             latin: 'Petunia × atkinsiana',     category: 'flower', light: 'direct',  waterSummer: 2, waterWinter: 5,  mist: null, fertilize: 14, outdoor: true,  icon: 'flowerBunch', details: 'trumpet-shaped violet petunia blooms spilling over', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'sunflower',       name: 'Sunflower (dwarf)',   latin: 'Helianthus annuus',        category: 'flower', light: 'direct',  waterSummer: 2, waterWinter: 4,  mist: null, fertilize: 14, outdoor: true,  icon: 'daisy', details: 'a golden sunflower face on a sturdy stem', pot: 'grow bag', potColor: 'sand beige' },
  { id: 'dahlia',          name: 'Dahlia',              latin: 'Dahlia pinnata',           category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 21, outdoor: true,  icon: 'rose', details: 'a geometric many-petaled dahlia bloom', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'chrysanthemum',   name: 'Chrysanthemum',       latin: 'Chrysanthemum morifolium', category: 'flower', light: 'partial', waterSummer: 3, waterWinter: 5,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'a dome of tightly packed amber blooms', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'pansy',           name: 'Pansy',               latin: 'Viola × wittrockiana',     category: 'flower', light: 'partial', waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 30, outdoor: true,  icon: 'flowerBunch', details: 'velvety two-tone pansy faces', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'snapdragon',      name: 'Snapdragon',          latin: 'Antirrhinum majus',        category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'tall spikes of ruffled snapdragon blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'cosmos',          name: 'Cosmos',              latin: 'Cosmos bipinnatus',        category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 8,  mist: null, fertilize: 30, outdoor: true,  icon: 'daisy', details: 'airy pink cosmos flowers over lacy foliage', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'impatiens',       name: 'Impatiens',           latin: 'Impatiens walleriana',     category: 'flower', light: 'shade',   waterSummer: 2, waterWinter: 5,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'a mound of flat coral impatiens blooms', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'fuchsia',         name: 'Fuchsia',             latin: 'Fuchsia magellanica',      category: 'flower', light: 'partial', waterSummer: 3, waterWinter: 5,  mist: null, fertilize: 14, outdoor: true,  icon: 'flowerBunch', details: 'dangling two-tone pink lantern flowers', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'azalea',          name: 'Azalea',              latin: 'Rhododendron simsii',      category: 'flower', light: 'partial', waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 30, outdoor: true,  icon: 'flowerBunch', details: 'a shrub smothered in rosy azalea blooms', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'camellia',        name: 'Camellia',            latin: 'Camellia japonica',        category: 'flower', light: 'partial', waterSummer: 4, waterWinter: 7,  mist: null, fertilize: 30, outdoor: true,  icon: 'rose', details: 'perfect spiral blooms among glossy leaves', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'gardenia',        name: 'Gardenia',            latin: 'Gardenia jasminoides',     category: 'flower', light: 'partial', waterSummer: 4, waterWinter: 7,  mist: 5,    fertilize: 21, outdoor: true,  icon: 'rose', details: 'creamy fragrant gardenia blooms', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'jasmine',         name: 'Jasmine',             latin: 'Jasminum polyanthum',      category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 7,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'starry white jasmine flowers on a twining vine', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'cyclamen',        name: 'Cyclamen',            latin: 'Cyclamen persicum',        category: 'flower', light: 'partial', waterSummer: 5, waterWinter: 9,  mist: null, fertilize: 30, outdoor: true,  icon: 'tulip', details: 'swept-back magenta petals over marbled leaves', pot: 'small ceramic pot', potColor: 'cream white' },
  { id: 'poinsettia',      name: 'Poinsettia',          latin: 'Euphorbia pulcherrima',    category: 'flower', light: 'partial', waterSummer: 5, waterWinter: 9,  mist: null, fertilize: 30, outdoor: false, icon: 'rose', details: 'scarlet star-shaped leaf bracts', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'amaryllis',       name: 'Amaryllis',           latin: 'Hippeastrum hybridum',     category: 'flower', light: 'direct',  waterSummer: 6, waterWinter: 12, mist: null, fertilize: 30, outdoor: false, icon: 'tulip', details: 'huge trumpet blooms on a thick hollow stalk', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'carnation',       name: 'Carnation',           latin: 'Dianthus caryophyllus',    category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 7,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'frilly pink carnation blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'lantana',         name: 'Lantana',             latin: 'Lantana camara',           category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 8,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'confetti-colored flower clusters', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'salvia',          name: 'Salvia',              latin: 'Salvia splendens',         category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 8,  mist: null, fertilize: 30, outdoor: true,  icon: 'flowerBunch', details: 'upright spikes of scarlet salvia', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'verbena',         name: 'Verbena',             latin: 'Verbena × hybrida',        category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 6,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'domed clusters of tiny violet blooms', pot: 'hanging pot', potColor: 'cream white' },
  { id: 'nasturtium',      name: 'Nasturtium',          latin: 'Tropaeolum majus',         category: 'flower', light: 'direct',  waterSummer: 4, waterWinter: 7,  mist: null, fertilize: 30, outdoor: true,  icon: 'flowerBunch', details: 'round lily-pad leaves and orange trumpet blooms', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'sweet-pea',       name: 'Sweet Pea',           latin: 'Lathyrus odoratus',        category: 'flower', light: 'direct',  waterSummer: 3, waterWinter: 5,  mist: null, fertilize: 21, outdoor: true,  icon: 'flowerBunch', details: 'ruffled pastel sweet pea blossoms on tendrils', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'peony',           name: 'Peony (potted)',      latin: 'Paeonia lactiflora',       category: 'flower', light: 'partial', waterSummer: 4, waterWinter: 8,  mist: null, fertilize: 30, outdoor: true,  icon: 'rose', details: 'a lush blush-pink peony bloom', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'lavender',        name: 'Lavender',            latin: 'Lavandula angustifolia',   category: 'flower', light: 'direct',  waterSummer: 7, waterWinter: 14, mist: null, fertilize: 30, outdoor: true,  icon: 'flowerBunch', details: 'slim stems with purple lavender spikes', pot: 'terracotta pot', potColor: 'warm orange' },

  /* ── herbs & edible ── */
  { id: 'basil',           name: 'Basil',               latin: 'Ocimum basilicum',         category: 'herb', light: 'direct',  waterSummer: 2, waterWinter: 4,  mist: null, fertilize: 21, outdoor: true, icon: 'sprout', details: 'bright green fragrant basil leaves', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'mint',            name: 'Mint',                latin: 'Mentha spicata',           category: 'herb', light: 'partial', waterSummer: 3, waterWinter: 5,  mist: null, fertilize: 21, outdoor: true, icon: 'sprout', details: 'a bushy tuft of toothed mint leaves', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'rosemary',        name: 'Rosemary',            latin: 'Salvia rosmarinus',        category: 'herb', light: 'direct',  waterSummer: 5, waterWinter: 10, mist: null, fertilize: 30, outdoor: true, icon: 'grassy', details: 'upright needle-leaf rosemary sprigs', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'cilantro',        name: 'Cilantro',            latin: 'Coriandrum sativum',       category: 'herb', light: 'partial', waterSummer: 3, waterWinter: 5,  mist: null, fertilize: 21, outdoor: true, icon: 'sprout', details: 'lacy flat cilantro leaves', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'parsley',         name: 'Parsley',             latin: 'Petroselinum crispum',     category: 'herb', light: 'partial', waterSummer: 3, waterWinter: 5,  mist: null, fertilize: 21, outdoor: true, icon: 'sprout', details: 'curly bright parsley tufts', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'thyme',           name: 'Thyme',               latin: 'Thymus vulgaris',          category: 'herb', light: 'direct',  waterSummer: 7, waterWinter: 12, mist: null, fertilize: 30, outdoor: true, icon: 'sprout', details: 'a low mat of tiny thyme leaves', pot: 'shallow bonsai dish', potColor: 'warm orange' },
  { id: 'oregano',         name: 'Oregano',             latin: 'Origanum vulgare',         category: 'herb', light: 'direct',  waterSummer: 6, waterWinter: 10, mist: null, fertilize: 30, outdoor: true, icon: 'sprout', details: 'sprawling stems of small oval oregano leaves', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'chives',          name: 'Chives',              latin: 'Allium schoenoprasum',     category: 'herb', light: 'partial', waterSummer: 4, waterWinter: 7,  mist: null, fertilize: 21, outdoor: true, icon: 'grassy', details: 'a tuft of slender hollow chive blades', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'sage',            name: 'Sage',                latin: 'Salvia officinalis',       category: 'herb', light: 'direct',  waterSummer: 6, waterWinter: 10, mist: null, fertilize: 30, outdoor: true, icon: 'sprout', details: 'soft grey-green velvety sage leaves', pot: 'terracotta pot', potColor: 'sand beige' },
  { id: 'chili-pepper',    name: 'Chili Pepper',        latin: 'Capsicum annuum',          category: 'herb', light: 'direct',  waterSummer: 2, waterWinter: 4,  mist: null, fertilize: 14, outdoor: true, icon: 'sprout', details: 'a compact plant studded with red chili pods', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'tomato',          name: 'Tomato',              latin: 'Solanum lycopersicum',     category: 'herb', light: 'direct',  waterSummer: 2, waterWinter: 3,  mist: null, fertilize: 14, outdoor: true, icon: 'sprout', details: 'a vine with small red tomatoes', pot: 'grow bag', potColor: 'sand beige' },
  { id: 'strawberry',      name: 'Strawberry',          latin: 'Fragaria × ananassa',      category: 'herb', light: 'direct',  waterSummer: 2, waterWinter: 4,  mist: null, fertilize: 14, outdoor: true, icon: 'sprout', details: 'trailing runners with red berries and white blooms', pot: 'hanging pot', potColor: 'warm orange' },
  { id: 'lemon-tree',      name: 'Lemon Tree (potted)', latin: 'Citrus × limon',           category: 'herb', light: 'direct',  waterSummer: 4, waterWinter: 8,  mist: null, fertilize: 21, outdoor: true, icon: 'tree', details: 'a small citrus tree with bright lemons', pot: 'terracotta pot', potColor: 'warm orange' },

  /* ── trees & palms ── */
  { id: 'fiddle-leaf',     name: 'Fiddle Leaf Fig',     latin: 'Ficus lyrata',             category: 'tree', light: 'direct',  waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 30, outdoor: false, icon: 'tree', details: 'large violin-shaped glossy leaves on a slim trunk', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'rubber-plant',    name: 'Rubber Plant',        latin: 'Ficus elastica',           category: 'tree', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 30, outdoor: false, icon: 'tree', details: 'broad deep-green rubbery leaves', pot: 'ceramic pot', potColor: 'charcoal grey' },
  { id: 'bonsai-ficus',    name: 'Bonsai (Ficus)',      latin: 'Ficus retusa',             category: 'tree', light: 'direct',  waterSummer: 3,  waterWinter: 5,  mist: 3,    fertilize: 30, outdoor: true,  icon: 'bonsai', details: 'a sculpted miniature tree with cloud-shaped canopy', pot: 'shallow bonsai dish', potColor: 'warm orange' },
  { id: 'schefflera',      name: 'Umbrella Plant',      latin: 'Schefflera arboricola',    category: 'tree', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 30, outdoor: false, icon: 'tree', details: 'glossy umbrella-shaped leaf clusters', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'money-tree',      name: 'Money Tree',          latin: 'Pachira aquatica',         category: 'tree', light: 'partial', waterSummer: 8,  waterWinter: 14, mist: 7,    fertilize: 30, outdoor: false, icon: 'tree', details: 'a braided trunk topped with hand-shaped leaves', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'ficus-benjamina', name: 'Weeping Fig',         latin: 'Ficus benjamina',          category: 'tree', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 30, outdoor: false, icon: 'tree', details: 'a graceful tree of small glossy pointed leaves', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'norfolk-pine',    name: 'Norfolk Island Pine', latin: 'Araucaria heterophylla',   category: 'tree', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 45, outdoor: false, icon: 'tree', details: 'tiered soft-needled evergreen branches', pot: 'ceramic pot', potColor: 'charcoal grey' },
  { id: 'ponytail-palm',   name: 'Ponytail Palm',       latin: 'Beaucarnea recurvata',     category: 'tree', light: 'direct',  waterSummer: 12, waterWinter: 25, mist: null, fertilize: 60, outdoor: false, icon: 'grassy', details: 'a bulbous trunk with a fountain of curly leaves', pot: 'ceramic pot', potColor: 'sand beige' },
  { id: 'areca-palm',      name: 'Areca Palm',          latin: 'Dypsis lutescens',         category: 'tree', light: 'partial', waterSummer: 6,  waterWinter: 10, mist: 7,    fertilize: 30, outdoor: false, icon: 'palm', details: 'feathery arching palm fronds', pot: 'ceramic pot', potColor: 'cream white' },
  { id: 'parlor-palm',     name: 'Parlor Palm',         latin: 'Chamaedorea elegans',      category: 'tree', light: 'shade',   waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 45, outdoor: false, icon: 'palm', details: 'delicate bamboo-like palm fronds', pot: 'terracotta pot', potColor: 'warm orange' },
  { id: 'kentia-palm',     name: 'Kentia Palm',         latin: 'Howea forsteriana',        category: 'tree', light: 'partial', waterSummer: 7,  waterWinter: 12, mist: 7,    fertilize: 45, outdoor: false, icon: 'palm', details: 'tall elegant drooping palm fronds', pot: 'ceramic pot', potColor: 'charcoal grey' },
  { id: 'bird-of-paradise', name: 'Bird of Paradise',   latin: 'Strelitzia reginae',       category: 'tree', light: 'direct',  waterSummer: 6,  waterWinter: 10, mist: 7,    fertilize: 30, outdoor: true,  icon: 'palm', details: 'banana-like leaves and an orange crane flower', pot: 'ceramic pot', potColor: 'cream white' },
]

// Plants imported from the online search live in app state; the store registers
// them here so getCatalogPlant() works everywhere without threading state through.
let customCatalog = new Map()

export function setCustomCatalog(entries) {
  customCatalog = new Map((entries || []).map(e => [e.id, e]))
}

export function getCatalogPlant(id) {
  return CATALOG.find(p => p.id === id) || customCatalog.get(id) || null
}

// How well a room's light suits a plant (Planta-style match tags).
// One step apart is livable; two steps (direct-sun plant in shade, or a
// shade plant in full sun) is asking for trouble.
const LIGHT_ORDER = { direct: 0, partial: 1, shade: 2 }

export function lightMatch(plantLight, zoneLight) {
  const d = Math.abs((LIGHT_ORDER[plantLight] ?? 1) - (LIGHT_ORDER[zoneLight] ?? 1))
  if (d === 0) return { label: 'Ideal', cls: 'ok' }
  if (d === 1) return { label: 'Acceptable', cls: 'soon' }
  return { label: 'Not recommended', cls: 'due' }
}
